MAKEFILE = Makefile.win

all:
	for dir in swe base jyotish dialogs pdf gui; do \
		cd $$dir; \
		make -f $(MAKEFILE); \
		cd ..; \
	done

clean:
	for dir in base swe jyotish dialogs pdf gui; do \
		cd $$dir; \
		make -f $(MAKEFILE) clean; \
		cd ..; \
	done



